kind: pipeline
type: docker
name: default

workspace:
    base: /go
    path: src/github.com/leiless/dnsredir

clone:
  depth: 1

steps:
- name: prepare
  image: golang
  commands:
    - export COREDNS_DIR=/go/src/github.com/coredns/coredns
    - export COREDNS_URL=https://github.com/coredns/coredns.git
    # Get the latest tag name
    - TAG_NAME=$(curl --silent https://api.github.com/repos/coredns/coredns/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
    # Do a shallow clone, silent "You are in 'detached HEAD' state..."
    - git clone --branch $TAG_NAME --depth 1 $COREDNS_URL $COREDNS_DIR 2> /dev/null
    - cd $COREDNS_DIR
    - make

