kind: pipeline
type: docker
name: default

workspace:
    base: /go
    path: src/github.com/leiless/dnsredir

clone:
  depth: 1

steps:
- name: prepare
  image: golang
  commands:
    - set -euf
    - uname -a
    - go version
    - go env
    - rm -f go.mod go.sum
    - export DNSREDIR_DIR=/go/src/github.com/leiless/dnsredir
    - export BIN=$DNSREDIR_DIR/bin
    - mkdir -p $BIN
    - export COREDNS_DIR=/go/src/github.com/coredns/coredns
    - export COREDNS_URL=https://github.com/coredns/coredns.git
    # Get the latest tag name
    - TAG_NAME=$(curl --silent https://api.github.com/repos/coredns/coredns/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
    # Do a shallow clone, silent "You are in 'detached HEAD' state..."
    - git clone --branch $TAG_NAME --depth 1 $COREDNS_URL $COREDNS_DIR 2> /dev/null
    - cd $COREDNS_DIR
    - sed -i 's|BUILDOPTS:=-v|BUILDOPTS:=-v -race|g' Makefile
    - sed -i 's|CGO_ENABLED:=0|CGO_ENABLED:=1|g' Makefile
    - sed -i 's|forward:forward|forward:forward\\\\ndnsredir:dnsredir|g' plugin.cfg
    - git diff
    - ln -s $DNSREDIR_DIR $COREDNS_DIR/plugin/$(basename $DNSREDIR_DIR)
- name: build-coredns-linux-amd64
  image: golang
  environment:
    GOOS: linux
    GOARCH: amd64
  commands:
    - cd /go/src/github.com/coredns/coredns
    - make
    - mv coredns /go/src/github.com/leiless/dnsredir/bin/coredns_dnsredir-$GOOS-$GOARCH
- name: build-coredns-linux-arm
  image: golang
  environment:
    GOOS: linux
    GOARCH: arm
  commands:
    - cd /go/src/github.com/coredns/coredns
    # -race is only supported on 64-bit arch
    - make CGO_ENABLED=0 BUILDOPTS=-v
    - mv coredns /go/src/github.com/leiless/dnsredir/bin/coredns_dnsredir-$GOOS-$GOARCH
- name: build-coredns-linux-arm64
  image: golang
  environment:
    GOOS: linux
    GOARCH: arm64
  commands:
    - cd /go/src/github.com/coredns/coredns
    # Silent "Error: no such instruction: ..."
    - make CGO_ENABLED=0 BUILDOPTS=-v
    - mv coredns /go/src/github.com/leiless/dnsredir/bin/coredns_dnsredir-$GOOS-$GOARCH
- name: build-coredns-darwin-amd64
  image: golang
  environment:
    GOOS: darwin
    GOARCH: amd64
  commands:
    - cd /go/src/github.com/coredns/coredns
    - make CGO_ENABLED=0 BUILDOPTS=-v
    - mv coredns /go/src/github.com/leiless/dnsredir/bin/coredns_dnsredir-$GOOS-$GOARCH
- name: build-coredns-windows-amd64
  image: golang
  environment:
    GOOS: windows
    GOARCH: amd64
  commands:
    - cd /go/src/github.com/coredns/coredns
    - make
    - mv coredns /go/src/github.com/leiless/dnsredir/bin/coredns_dnsredir-$GOOS-$GOARCH
- name: calc-shasum256
  image: alpine
  commands:
    - uname -a
    - cd /go/src/github.com/leiless/dnsredir/bin
    - sha256sum coredns* | tee shasum256.txt

