name: coredns-dnsredir auto build

on:
  push:
    branches: [ master, dev ]
    paths:
      - '**.go'
      - '**.h'
      - '**.c'
      - '**.sh'
      - '**.yml'
      - '**.mod'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build-on-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Prepare CoreDNS for dnsredir plugin
        run: |
          set -eufx
          whoami
          nproc
          uname -v

          DNSREDIR_DIR=$PWD
          REPO_ADDR=$(git remote get-url origin | sed -e 's/^https:\/\///' -e 's/\.git//')
          HEAD_COMMIT=$(git describe --dirty --always)
          DNSREDIR_TAG=$(curl -sL https://api.github.com/repos/leiless/dnsredir/releases/latest | grep '"tag_name":' | cut -d'"' -f4)

          COREDNS_URL=https://github.com/coredns/coredns.git
          COREDNS_DIR=$HOME/coredns
          COREDNS_TAG=$(curl -sL https://api.github.com/repos/coredns/coredns/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
          git clone --branch $COREDNS_TAG --depth 1 $COREDNS_URL $COREDNS_DIR 2> /dev/null

          mkdir -p ~/go/pkg/mod/github.com/leiless
          # Link leiless/dnsredir to latest master tree.
          ln -s $DNSREDIR_DIR ~/go/pkg/mod/github.com/leiless/dnsredir@$DNSREDIR_TAG

          pushd $COREDNS_DIR
          sed -i "s|forward:forward|dnsredir:$REPO_ADDR\nforward:forward|g" plugin.cfg
          sed -i "s|GITCOMMIT:=|CUSTOM_FLAGS=-X $REPO_ADDR.pluginVersion=$DNSREDIR_TAG -X $REPO_ADDR.pluginHeadCommit=$HEAD_COMMIT\\nGITCOMMIT:=|g" Makefile
          sed -i 's|$(GITCOMMIT)|$(GITCOMMIT) $(CUSTOM_FLAGS)|g' Makefile
          go generate coredns.go
          git diff
          git status
          # see: https://github.com/golang/go/issues/44129
          go get -t .
          #go get
          popd

      - name: Debug build
        env:
          GOOS: linux
          GOARCH: amd64
          # Disable code optimization
          CGO_CFLAGS: -g -O0 -DDEBUG
          CGO_CXXFLAGS: -g -O0 -DDEBUG
        run: |
          set -eufx
          COREDNS_DIR=$HOME/coredns
          pushd $COREDNS_DIR
          make CGO_ENABLED=1 BUILDOPTS="-v -race" -j$(nproc)
          popd

  build-on-darwin:
    name: Build on Darwin
    runs-on: macos-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: ^1.13

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Get dependencies
        run: |
          go get -v -t -d ./...
          if [ -f Gopkg.toml ]; then
              curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
              dep ensure
          fi

      - name: Prepare CoreDNS for dnsredir plugin
        run: |
          set -eufx
          whoami
          sysctl -n hw.model
          sysctl -n hw.ncpu
          sysctl -n hw.memsize
          sysctl -n machdep.cpu.brand_string
          sw_vers
          uname -v
          xcode-select -p
          xcodebuild -version

          DNSREDIR_DIR=$PWD
          REPO_ADDR=$(git remote get-url origin | sed -e 's/^https:\/\///' -e 's/\.git//')
          HEAD_COMMIT=$(git describe --dirty --always)
          DNSREDIR_TAG=$(curl -sL https://api.github.com/repos/leiless/dnsredir/releases/latest | grep '"tag_name":' | cut -d'"' -f4)

          pushd pf
          ./download-pf-headers.sh
          popd

          COREDNS_URL=https://github.com/coredns/coredns.git
          COREDNS_DIR=$HOME/coredns
          COREDNS_TAG=$(curl -sL https://api.github.com/repos/coredns/coredns/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
          git clone --branch $COREDNS_TAG --depth 1 $COREDNS_URL $COREDNS_DIR 2> /dev/null

          mkdir -p ~/go/pkg/mod/github.com/leiless
          # Link leiless/dnsredir to latest master tree.
          ln -s $DNSREDIR_DIR ~/go/pkg/mod/github.com/leiless/dnsredir@$DNSREDIR_TAG

          pushd $COREDNS_DIR
          sed -i '' "s|forward:forward|dnsredir:$REPO_ADDR\nforward:forward|g" plugin.cfg
          sed -i '' "s|GITCOMMIT:=|CUSTOM_FLAGS=-X $REPO_ADDR.pluginVersion=$DNSREDIR_TAG -X $REPO_ADDR.pluginHeadCommit=$HEAD_COMMIT\\nGITCOMMIT:=|g" Makefile
          sed -i '' 's|$(GITCOMMIT)|$(GITCOMMIT) $(CUSTOM_FLAGS)|g' Makefile
          go generate coredns.go
          git diff
          git status
          go get
          popd

      - name: Debug build
        env:
          GOOS: darwin
          GOARCH: arm64
          CGO_CFLAGS: -g -O0 -DDEBUG
          CGO_CXXFLAGS: -g -O0 -DDEBUG
        run: |
          set -eufx

          # Hack macOS 10.x to allow arm64* build support
          if [ "$(sw_vers -productVersion | cut -d'.' -f1)" = 10 ]; then
            pushd /Library/Developer/CommandLineTools/SDKs
            sudo rm MacOSX.sdk
            sudo ln -s MacOSX11.1.sdk MacOSX.sdk
            sudo rm -rf MacOSX10.15.sdk
            ls -l
            popd
          fi

          COREDNS_DIR=$HOME/coredns
          pushd $COREDNS_DIR
          #make CGO_ENABLED=1 BUILDOPTS="-v -race" -j$(sysctl -n hw.ncpu)
          # runtime.*: relocation target __tsan_* not defined
          make CGO_ENABLED=1 BUILDOPTS="-v" -j$(sysctl -n hw.ncpu)
          popd
