name: Non-release build CI

on:
  push:
    branches: [ master ]
    paths:
      - '**.go'
      - '**.h'
      - '**.c'
      - '**.sh'
      - '**.yml'
      - '**.mod'
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs:
  build-on-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Prepare CoreDNS for dnsredir plugin
      run: |
        set -eufx
        nproc
        uname -a
        env
        go version
        go env

        DNSREDIR_DIR=$PWD
        REPO_ADDR=$(git remote get-url origin | sed -e 's/^https:\/\///' -e 's/\.git//')
        HEAD_COMMIT=$(git describe --dirty --always)
        DNSREDIR_TAG=$(curl -sL https://api.github.com/repos/leiless/dnsredir/releases/latest | grep '"tag_name":' | cut -d'"' -f4)

        mkdir -p $HOME/coredns
        COREDNS_URL=https://github.com/coredns/coredns.git
        COREDNS_DIR=$HOME/coredns/coredns
        COREDNS_TAG=$(curl -sL https://api.github.com/repos/coredns/coredns/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
        git clone --branch $COREDNS_TAG --depth 1 $COREDNS_URL $COREDNS_DIR 2> /dev/null

        pushd $COREDNS_DIR
        sed -i 's|forward:forward|dnsredir:$REPO_ADDR\nforward:forward|g' plugin.cfg
        sed -i "s|GITCOMMIT:=|CUSTOM_FLAGS=-X $REPO_ADDR.pluginVersion=$DNSREDIR_TAG -X $REPO_ADDR.pluginHeadCommit=$HEAD_COMMIT\\nGITCOMMIT:=|g" Makefile
        sed -i 's|$(GITCOMMIT)|$(GITCOMMIT) $(CUSTOM_FLAGS)|g' Makefile
        go generate coredns.go
        git diff
        git status
        popd

        mkdir -p ~/go/pkg/mod/github.com/leiless
        # Link leiless/dnsredir to latest master tree.
        ln -s $DNSREDIR_DIR ~/go/pkg/mod/github.com/leiless/dnsredir@$DNSREDIR_TAG

    - name: Debug build
      env:
        GOOS: linux
        GOARCH: amd64
        # Disable code optimization
        CGO_CFLAGS: -g -O0 -DDEBUG
        CGO_CXXFLAGS: -g -O0 -DDEBUG
      run: |
        set -eufx
        pushd $HOME/coredns/coredns
        make CGO_ENABLED=1 BUILDOPTS="-v -race" -j$(nproc)
        popd

  build-on-darwin:
    name: Build on Darwin
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Prepare CoreDNS for dnsredir plugin
      run: |
        set -eufx
        sysctl -n hw.ncpu
        sw_vers
        uname -a
        env
        go version
        go env

        # [quote] GNU "sed" has been installed as "gsed".
        brew install gnu-sed

        DNSREDIR_DIR=$PWD
        HEAD_COMMIT=$(git describe --dirty --always)
        DNSREDIR_TAG=$(curl -sL https://api.github.com/repos/leiless/dnsredir/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
        
        pushd pf
        ./download-pf-headers.sh
        popd

        mkdir -p $HOME/coredns
        COREDNS_URL=https://github.com/coredns/coredns.git
        COREDNS_DIR=$HOME/coredns/coredns
        COREDNS_TAG=$(curl -sL https://api.github.com/repos/coredns/coredns/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
        git clone --branch $COREDNS_TAG --depth 1 $COREDNS_URL $COREDNS_DIR 2> /dev/null

        pushd $COREDNS_DIR
        gsed -i 's|forward:forward|dnsredir:dnsredir\nforward:forward|g' plugin.cfg
        MOD_ADDR=github.com/coredns/coredns/plugin/dnsredir
        gsed -i "s|GITCOMMIT:=|CUSTOM_FLAGS=-X $MOD_ADDR.pluginVersion=$DNSREDIR_TAG -X $MOD_ADDR.pluginHeadCommit=$HEAD_COMMIT\\nGITCOMMIT:=|g" Makefile
        gsed -i 's|$(GITCOMMIT)|$(GITCOMMIT) $(CUSTOM_FLAGS)|g' Makefile
        go generate coredns.go
        gsed -i 's|_ "dnsredir"|_ "github.com/leiless/dnsredir"|g' core/plugin/zplugin.go
        git diff
        git status
        popd

        mkdir -p ~/go/pkg/mod/github.com/leiless
        # Link leiless/dnsredir to latest master tree.
        ln -s $DNSREDIR_DIR ~/go/pkg/mod/github.com/leiless/dnsredir@$DNSREDIR_TAG

    - name: Debug build
      env:
        GOOS: darwin
        GOARCH: amd64
        CGO_CFLAGS: -g -O0 -DDEBUG
        CGO_CXXFLAGS: -g -O0 -DDEBUG
      run: |
        set -eufx
        pushd $HOME/coredns/coredns
        make CGO_ENABLED=1 BUILDOPTS="-v -race" -j$(sysctl -n hw.ncpu)
        popd
