name: CoreDNS dnsredir CI on tagging

on:
  push:
    tags: v*

jobs:

  # see: https://github.com/actions/create-release
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: true
          prerelease: true

  build-on-linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Prepare CoreDNS for dnsredir plugin
      run: |
        set -eufx
        nproc
        env
        uname -a
        go version
        go env

        DNSREDIR_DIR=$PWD
        HEAD_COMMIT=$(git describe --dirty --always)
        DNSREDIR_TAG=$(curl -sL https://api.github.com/repos/leiless/dnsredir/releases/latest | grep '"tag_name":' | cut -d'"' -f4)

        mkdir -p $HOME/coredns
        COREDNS_URL=https://github.com/coredns/coredns.git
        COREDNS_DIR=$HOME/coredns/coredns
        COREDNS_TAG=$(curl -sL https://api.github.com/repos/coredns/coredns/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
        git clone --branch $COREDNS_TAG --depth 1 $COREDNS_URL $COREDNS_DIR 2> /dev/null

        pushd $COREDNS_DIR
        mkdir -p bin
        sed -i 's|forward:forward|dnsredir:dnsredir\nforward:forward|g' plugin.cfg
        MOD_ADDR=github.com/coredns/coredns/plugin/dnsredir
        sed -i "s|GITCOMMIT:=|CUSTOM_FLAGS=-X $MOD_ADDR.pluginVersion=$DNSREDIR_TAG -X $MOD_ADDR.pluginHeadCommit=$HEAD_COMMIT\\nGITCOMMIT:=|g" Makefile
        sed -i 's|$(GITCOMMIT)|$(GITCOMMIT) $(CUSTOM_FLAGS)|g' Makefile
        go generate coredns.go
        sed -i 's|_ "dnsredir"|_ "github.com/leiless/dnsredir"|g' core/plugin/zplugin.go
        git diff
        git status
        popd

        mkdir -p ~/go/pkg/mod/github.com/leiless
        # Link leiless/dnsredir to latest master tree.
        ln -s $DNSREDIR_DIR ~/go/pkg/mod/github.com/leiless/dnsredir@$DNSREDIR_TAG

    - name: Debug build
      env:
        GOOS: linux
        GOARCH: amd64
        # Disable code optimization
        CGO_CFLAGS: -g -O0 -DDEBUG
        CGO_CXXFLAGS: -g -O0 -DDEBUG
      run: |
        set -eufx
        COREDNS_DIR=$HOME/coredns/coredns
        pushd $COREDNS_DIR
        make CGO_ENABLED=1 BUILDOPTS="-v -race" -j$(nproc)
        mv coredns bin/coredns_dnsredir-$GOOS-$GOARCH-debug
        popd

    - name: Release build
      env:
        GOOS: linux
        GOARCH: amd64
      run: |
        set -eufx
        COREDNS_DIR=$HOME/coredns/coredns
        pushd $COREDNS_DIR
        make -j$(nproc)
        mv coredns bin/coredns_dnsredir-$GOOS-$GOARCH
        popd

    - name: Release build for ARM
      env:
        GOOS: linux
        GOARCH: arm
      run: |
        set -eufx
        COREDNS_DIR=$HOME/coredns/coredns
        pushd $COREDNS_DIR
        make -j$(nproc)
        mv coredns bin/coredns_dnsredir-$GOOS-$GOARCH
        popd

    - name: Release build for ARM64
      env:
        GOOS: linux
        GOARCH: arm64
      run: |
        set -eufx
        COREDNS_DIR=$HOME/coredns/coredns
        pushd $COREDNS_DIR
        make -j$(nproc)
        mv coredns bin/coredns_dnsredir-$GOOS-$GOARCH
        popd

    - name: Release build for Windows
      env:
        GOOS: windows
        GOARCH: amd64
      run: |
        set -eufx
        COREDNS_DIR=$HOME/coredns/coredns
        pushd $COREDNS_DIR
        make -j$(nproc)
        mv coredns bin/coredns_dnsredir-$GOOS-$GOARCH
        popd

    - name: Upload files
      run: |
        set -eufx
        COREDNS_DIR=$HOME/coredns/coredns
        pushd $COREDNS_DIR
        ls -1 | xargs -I{} zip -q9 {}.zip {}
        ls -1 | grep -v "\.zip$" | xargs rm
        ls -l
        popd

    # see:
    #   https://github.com/actions/upload-release-asset
    #   htps://github.com/marketplace/actions/upload-a-release-asset
    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ jobs.create-release.steps.create_release.outputs.upload_url }}
        asset_path: $HOME/coredns/coredns/bin/*
        asset_content_type: application/zip

  build-on-darwin:
    name: Build on Darwin
    runs-on: macos-latest
    steps:

    - name: Set up Go 1.x
      uses: actions/setup-go@v2
      with:
        go-version: ^1.13

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Get dependencies
      run: |
        go get -v -t -d ./...
        if [ -f Gopkg.toml ]; then
            curl https://raw.githubusercontent.com/golang/dep/master/install.sh | sh
            dep ensure
        fi

    - name: Prepare CoreDNS for dnsredir plugin
      run: |
        set -eufx
        sysctl -n hw.ncpu
        sw_vers
        uname -a
        env
        go version
        go env

        # [quote] GNU "sed" has been installed as "gsed".
        brew install gnu-sed

        DNSREDIR_DIR=$PWD
        HEAD_COMMIT=$(git describe --dirty --always)
        DNSREDIR_TAG=$(curl -sL https://api.github.com/repos/leiless/dnsredir/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
        
        pushd pf
        ./download-pf-headers.sh
        popd

        mkdir -p $HOME/coredns
        COREDNS_URL=https://github.com/coredns/coredns.git
        COREDNS_DIR=$HOME/coredns/coredns
        COREDNS_TAG=$(curl -sL https://api.github.com/repos/coredns/coredns/releases/latest | grep '"tag_name":' | cut -d'"' -f4)
        git clone --branch $COREDNS_TAG --depth 1 $COREDNS_URL $COREDNS_DIR 2> /dev/null

        pushd $COREDNS_DIR
        mkdir -p bin
        gsed -i 's|forward:forward|dnsredir:dnsredir\nforward:forward|g' plugin.cfg
        MOD_ADDR=github.com/coredns/coredns/plugin/dnsredir
        gsed -i "s|GITCOMMIT:=|CUSTOM_FLAGS=-X $MOD_ADDR.pluginVersion=$DNSREDIR_TAG -X $MOD_ADDR.pluginHeadCommit=$HEAD_COMMIT\\nGITCOMMIT:=|g" Makefile
        gsed -i 's|$(GITCOMMIT)|$(GITCOMMIT) $(CUSTOM_FLAGS)|g' Makefile
        go generate coredns.go
        gsed -i 's|_ "dnsredir"|_ "github.com/leiless/dnsredir"|g' core/plugin/zplugin.go
        git diff
        git status
        popd

        mkdir -p ~/go/pkg/mod/github.com/leiless
        # Link leiless/dnsredir to latest master tree.
        ln -s $DNSREDIR_DIR ~/go/pkg/mod/github.com/leiless/dnsredir@$DNSREDIR_TAG

    - name: Debug build
      env:
        GOOS: darwin
        GOARCH: amd64
        CGO_CFLAGS: -g -O0 -DDEBUG
        CGO_CXXFLAGS: -g -O0 -DDEBUG
      run: |
        set -eufx
        COREDNS_DIR=$HOME/coredns/coredns
        pushd $COREDNS_DIR
        make CGO_ENABLED=1 BUILDOPTS="-v -race" -j$(sysctl -n hw.ncpu)
        mv coredns bin/coredns_dnsredir-$GOOS-$GOARCH-debug
        popd

    - name: Release build
      env:
        GOOS: darwin
        GOARCH: amd64
        CGO_CFLAGS: -O2
        CGO_CXXFLAGS: -O2
      run: |
        set -eufx
        COREDNS_DIR=$HOME/coredns/coredns
        pushd $COREDNS_DIR
        make CGO_ENABLED=1 BUILDOPTS="-v -race" -j$(sysctl -n hw.ncpu)
        mv coredns bin/coredns_dnsredir-$GOOS-$GOARCH
        popd

    - name: Post build
      run: |
        set -eufx
        COREDNS_DIR=$HOME/coredns/coredns
        pushd $COREDNS_DIR
        ls -l bin
        popd
